# Generated by Django 5.1.9 on 2025-07-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='rtsp_url',
            field=models.CharField(default='', help_text='RTSP URL for FFmpeg processing or go2rtc.', max_length=500),
        ),
        migrations.AlterField(
            model_name='camera',
            name='stream_id',
            field=models.CharField(default='', help_text='Used in go2rtc config (e.g., cam1)', max_length=100, unique=True),
        ),
    ]
