# Generated by Django 5.1.9 on 2025-07-16 13:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cams', '0002_camera_rtsp_url_alter_camera_stream_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(help_text='Camera stream ID', max_length=100)),
                ('farm_id', models.CharField(help_text='Farm/Location ID', max_length=100)),
                ('confidence', models.FloatField(help_text='Detection confidence (0.0 to 1.0)')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_path', models.CharField(blank=True, help_text='Path to detected frame', max_length=500, null=True)),
                ('is_resolved', models.BooleanField(default=False, help_text='Has this alert been handled?')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this detection')),
            ],
            options={
                'verbose_name': 'Fire Detection',
                'verbose_name_plural': 'Fire Detections',
                'ordering': ['-timestamp'],
            },
        ),
    ]
