# Generated by Django 5.1.9 on 2025-07-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cams', '0003_firedetection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firedetection',
            name='image_path',
        ),
        migrations.AddField(
            model_name='firedetection',
            name='bounding_box',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firedetection',
            name='image_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
