# Generated by Django 5.1.9 on 2025-07-24 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cams', '0004_remove_firedetection_image_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='stream_id',
            new_name='camera_id',
        ),
    ]
