# Generated by Django 5.1.9 on 2025-06-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_location_radius'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='radius',
        ),
    ]
